#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${COOMIA_ENV_FILE:-$ROOT/compose/.env}"

CURRENT_RELEASE="$(sed -n 's/^CURRENT_RELEASE=//p' "$ROOT/CURRENT_RELEASE")"
[[ "$CURRENT_RELEASE" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || {
  echo "error: CURRENT_RELEASE contains an invalid release identifier" >&2
  exit 1
}
APPLICATION_IMAGES_FILE="$ROOT/releases/$CURRENT_RELEASE/application-images.env"
INFRASTRUCTURE_IMAGES_FILE="$ROOT/releases/$CURRENT_RELEASE/infrastructure-images.env"
[[ -f "$APPLICATION_IMAGES_FILE" && -f "$INFRASTRUCTURE_IMAGES_FILE" ]] || {
  echo "error: CURRENT_RELEASE does not have a complete image catalog" >&2
  exit 1
}

catalog_value() {
  local name="$1" file="$2"
  sed -n "s/^${name}=//p" "$file"
}

PLATFORM_API_IMAGE="${PLATFORM_API_IMAGE:-$(catalog_value PLATFORM_API_IMAGE "$APPLICATION_IMAGES_FILE")}"
PLATFORM_UI_IMAGE="${PLATFORM_UI_IMAGE:-$(catalog_value PLATFORM_UI_IMAGE "$APPLICATION_IMAGES_FILE")}"
FLINK_LOCAL_IMAGE="${FLINK_LOCAL_IMAGE:-$(catalog_value FLINK_LOCAL_IMAGE "$APPLICATION_IMAGES_FILE")}"
POSTGRES_IMAGE="${POSTGRES_IMAGE:-$(catalog_value POSTGRES_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
OBJECT_STORAGE_IMAGE="${OBJECT_STORAGE_IMAGE:-$(catalog_value OBJECT_STORAGE_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
NESSIE_IMAGE="${NESSIE_IMAGE:-$(catalog_value NESSIE_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
TUGRAPH_IMAGE="${TUGRAPH_IMAGE:-$(catalog_value TUGRAPH_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
DORIS_FE_IMAGE="${DORIS_FE_IMAGE:-$(catalog_value DORIS_FE_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
DORIS_BE_IMAGE="${DORIS_BE_IMAGE:-$(catalog_value DORIS_BE_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
KAFKA_IMAGE="${KAFKA_IMAGE:-$(catalog_value KAFKA_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"
REDIS_IMAGE="${REDIS_IMAGE:-$(catalog_value REDIS_IMAGE "$INFRASTRUCTURE_IMAGES_FILE")}"

if [[ -e "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "error: $ENV_FILE already exists; use --force only after backing it up" >&2
  exit 1
fi

command -v openssl >/dev/null 2>&1 || {
  echo "error: openssl is required" >&2
  exit 1
}

secret() { openssl rand -hex "$1"; }

postgres_password="$(secret 24)"
home_data="${HOME:?HOME is required}/.local/share/coomia-platform"
umask 077
mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Shared image defaults from $CURRENT_RELEASE. Change them only when the
# publisher explicitly provides customer-specific immutable RepoDigests.
PLATFORM_API_IMAGE=$PLATFORM_API_IMAGE
PLATFORM_UI_IMAGE=$PLATFORM_UI_IMAGE
FLINK_LOCAL_IMAGE=$FLINK_LOCAL_IMAGE
POSTGRES_IMAGE=$POSTGRES_IMAGE
OBJECT_STORAGE_IMAGE=$OBJECT_STORAGE_IMAGE
NESSIE_IMAGE=$NESSIE_IMAGE
TUGRAPH_IMAGE=$TUGRAPH_IMAGE
DORIS_FE_IMAGE=$DORIS_FE_IMAGE
DORIS_BE_IMAGE=$DORIS_BE_IMAGE
KAFKA_IMAGE=$KAFKA_IMAGE
REDIS_IMAGE=$REDIS_IMAGE

POSTGRES_USER=platform
POSTGRES_PASSWORD=$postgres_password
POSTGRES_DB=platform
DATABASE_URL=postgresql+asyncpg://platform:$postgres_password@postgres:5432/platform
OBJECT_STORAGE_ACCESS_KEY=coomiaadmin
OBJECT_STORAGE_SECRET_KEY=$(secret 24)
DORIS_USER=root
DORIS_PASSWORD=$(secret 24)
REDIS_PASSWORD=$(secret 24)
TUGRAPH_USER=admin
TUGRAPH_PASSWORD=$(secret 24)
JWT_SECRET=$(secret 32)
DELIVERY_REPORT_HMAC_SECRET=$(secret 32)
DELIVERY_REPORT_HMAC_KEY_ID=v1
DELIVERY_REPORT_HMAC_PREVIOUS_KEYS={}
MDS_FLINK_CONTROL_TOKEN=$(secret 32)

LICENSE_MODE=online
LICENSE_SERVER_URL=https://coomia.com
COOMIA_LICENSE_PUBLIC_KEY_FILE=

MDS_FLINK_ARTIFACT_DIR=$home_data/flink-runtime
MDS_GENERATED_CONFIG_DIR=$home_data/generated
MDS_INTAKE_SECRETS_DIR=$home_data/intake-secrets
DOCKER_SOCKET_PATH=/var/run/docker.sock
BIND_ADDRESS=0.0.0.0
PLATFORM_UI_PORT=3000
PLATFORM_API_PORT=8050
CORS_ORIGINS=http://localhost:3000
INSTALL_WAIT_TIMEOUT_SECONDS=600
MDS_DATA_SUBNET=172.25.0.0/16
MDS_DATA_GATEWAY=172.25.0.1
DORIS_FE_IP=172.25.0.140
DORIS_BE_IP=172.25.0.141
EOF

chmod 600 "$ENV_FILE"
echo "created: $ENV_FILE"
echo "images: shared defaults loaded from $CURRENT_RELEASE"
echo "next: review environment-specific values, then run 'bash install.sh compose'"
