#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${COOMIA_ENV_FILE:-$ROOT/compose/.env}"

if [[ -e "$ENV_FILE" && "${1:-}" != "--force" ]]; then
  echo "error: $ENV_FILE already exists; use --force only after backing it up" >&2
  exit 1
fi

command -v openssl >/dev/null 2>&1 || {
  echo "error: openssl is required" >&2
  exit 1
}

secret() { openssl rand -hex "$1"; }

postgres_password="$(secret 24)"
home_data="${HOME:?HOME is required}/.local/share/coomia-platform"
umask 077
mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Fill every image field with the RepoDigest supplied for this release.
PLATFORM_API_IMAGE=
PLATFORM_UI_IMAGE=
FLINK_LOCAL_IMAGE=
POSTGRES_IMAGE=
OBJECT_STORAGE_IMAGE=
NESSIE_IMAGE=
TUGRAPH_IMAGE=
DORIS_FE_IMAGE=
DORIS_BE_IMAGE=
KAFKA_IMAGE=
REDIS_IMAGE=

POSTGRES_USER=platform
POSTGRES_PASSWORD=$postgres_password
POSTGRES_DB=platform
DATABASE_URL=postgresql+asyncpg://platform:$postgres_password@postgres:5432/platform
OBJECT_STORAGE_ACCESS_KEY=coomiaadmin
OBJECT_STORAGE_SECRET_KEY=$(secret 24)
DORIS_USER=root
DORIS_PASSWORD=$(secret 24)
REDIS_PASSWORD=$(secret 24)
TUGRAPH_USER=admin
TUGRAPH_PASSWORD=$(secret 24)
JWT_SECRET=$(secret 32)
DELIVERY_REPORT_HMAC_SECRET=$(secret 32)
DELIVERY_REPORT_HMAC_KEY_ID=v1
DELIVERY_REPORT_HMAC_PREVIOUS_KEYS={}
MDS_FLINK_CONTROL_TOKEN=$(secret 32)

LICENSE_MODE=online
LICENSE_SERVER_URL=https://coomia.com
COOMIA_LICENSE_PUBLIC_KEY_FILE=

MDS_FLINK_ARTIFACT_DIR=$home_data/flink-runtime
MDS_GENERATED_CONFIG_DIR=$home_data/generated
MDS_INTAKE_SECRETS_DIR=$home_data/intake-secrets
DOCKER_SOCKET_PATH=/var/run/docker.sock
BIND_ADDRESS=0.0.0.0
PLATFORM_UI_PORT=3000
PLATFORM_API_PORT=8050
CORS_ORIGINS=http://localhost:3000
INSTALL_WAIT_TIMEOUT_SECONDS=600
MDS_DATA_SUBNET=172.25.0.0/16
MDS_DATA_GATEWAY=172.25.0.1
DORIS_FE_IP=172.25.0.140
DORIS_BE_IP=172.25.0.141
EOF

chmod 600 "$ENV_FILE"
echo "created: $ENV_FILE"
echo "next: fill the image RepoDigests, then run 'bash install.sh compose'"
